name: CI

on:
  push:
    branches: ["dev", "main"]
  
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run flake8
        run: pip install flake8 && flake8 App/ Tests/
    
  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: run pytest
        run: pip install -r requirements.txt && python -m pytest
    
  build:
    name: build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t url-shortener .