name: deploy

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main, dev]
    types: 
      - completed

jobs:
  deploy-test:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev'
    name: deploy to test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: deploy to test
        run: echo "deploying to test environment"

  deploy-staging:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    name: deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy to staging
        run: echo "deploying to staging environment"

  deploy-prod:
    needs: deploy-staging
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    name: deploy to prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy to prod
        run: echo "deploying to prod environment"